services:
  api:
    image: yt-live-dungeon-api
    build:
      context: .
      dockerfile: docker/python/Dockerfile
      target: dev
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:${POSTGRES_PORT_CONTAINER}/${POSTGRES_DB}
      REDIS_URL: redis://redis:${REDIS_PORT_CONTAINER}
    ports:
      - "${API_PORT_HOST}:${API_PORT_CONTAINER}"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  postgres:
    image: yt-live-dungeon-postgres
    build:
      context: ./docker/postgres
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT_HOST}:${POSTGRES_PORT_CONTAINER}"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: yt-live-dungeon-redis
    build:
      context: ./docker/redis
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "${REDIS_PORT_HOST}:${REDIS_PORT_CONTAINER}"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
