services:
  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    env_file:
      - .env
    ports:
      - "${API_PORT_HOST}:${API_PORT_CONTAINER}"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  pgadmin:
    build:
      context: ./docker/pgadmin
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "${PGADMIN_PORT_HOST}:${PGADMIN_PORT_CONTAINER}"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  postgres:
    build:
      context: ./docker/postgres
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT_HOST}:${POSTGRES_PORT_CONTAINER}"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    build:
      context: ./docker/redis
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "${REDIS_PORT_HOST}:${REDIS_PORT_CONTAINER}"
    volumes:
      - redis_data:/data

volumes:
  pgadmin_data:
  postgres_data:
  redis_data:
