"""initial schema

Revision ID: 9b9080e6af23
Revises:
Create Date: 2026-08-12 00:32:38.017598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '9b9080e6af23'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE SCHEMA IF NOT EXISTS master")
    op.execute("CREATE SCHEMA IF NOT EXISTS runtime")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enemies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('enemy_key', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('base_max_hp', sa.Integer(), nullable=False),
    sa.Column('base_max_mp', sa.Integer(), nullable=False),
    sa.Column('base_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('weak_attribute', sa.String(length=2), nullable=True),
    sa.Column('break_max', sa.Integer(), nullable=False),
    sa.Column('ai_policy_key', sa.String(length=64), nullable=False),
    sa.Column('ai_policy_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.CheckConstraint("weak_attribute IS NULL OR weak_attribute IN ('RR', 'YR', 'YY', 'GY', 'GG', 'BG', 'BB', 'PB', 'PP', 'RP')", name=op.f('ck_enemies_weak_attribute_valid')),
    sa.CheckConstraint('break_max >= 0', name=op.f('ck_enemies_break_max_non_negative')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_enemies')),
    sa.UniqueConstraint('enemy_key', name=op.f('uq_enemies_enemy_key')),
    schema='master'
    )
    op.create_table('spells',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('command', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('attribute', sa.String(length=2), nullable=False),
    sa.Column('mp_cost', sa.Integer(), nullable=False),
    sa.Column('target_rule', sa.String(length=32), nullable=False),
    sa.Column('effects', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.CheckConstraint("attribute IN ('RR', 'YR', 'YY', 'GY', 'GG', 'BG', 'BB', 'PB', 'PP', 'RP')", name=op.f('ck_spells_attribute_valid')),
    sa.CheckConstraint("jsonb_typeof(effects) = 'array' AND jsonb_array_length(effects) >= 1", name=op.f('ck_spells_effects_non_empty_array')),
    sa.CheckConstraint('mp_cost >= 0', name=op.f('ck_spells_mp_cost_non_negative')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_spells')),
    sa.UniqueConstraint('command', name=op.f('uq_spells_command')),
    schema='master'
    )
    op.create_table('runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('state', sa.Enum('waiting', 'battle', 'camp', 'retire', 'game_over', name='run_state', schema='runtime'), nullable=False),
    sa.Column('current_floor', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_runs')),
    schema='runtime'
    )
    op.create_table('enemy_spells',
    sa.Column('enemy_id', sa.Integer(), nullable=False),
    sa.Column('spell_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['enemy_id'], ['master.enemies.id'], name=op.f('fk_enemy_spells_enemy_id_enemies')),
    sa.ForeignKeyConstraint(['spell_id'], ['master.spells.id'], name=op.f('fk_enemy_spells_spell_id_spells')),
    sa.PrimaryKeyConstraint('enemy_id', 'spell_id', name=op.f('pk_enemy_spells')),
    schema='master'
    )
    op.create_table('items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_key', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('attribute', sa.String(length=2), nullable=False),
    sa.Column('granted_spell_id', sa.Integer(), nullable=False),
    sa.Column('base_stat_modifiers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('per_level_stat_modifiers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('break_effects', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.CheckConstraint("attribute IN ('RR', 'YR', 'YY', 'GY', 'GG', 'BG', 'BB', 'PB', 'PP', 'RP')", name=op.f('ck_items_attribute_valid')),
    sa.ForeignKeyConstraint(['granted_spell_id'], ['master.spells.id'], name=op.f('fk_items_granted_spell_id_spells')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_items')),
    sa.UniqueConstraint('item_key', name=op.f('uq_items_item_key')),
    schema='master'
    )
    op.create_table('processed_commands',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('source_message_id', sa.String(length=256), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('viewer_id', sa.String(length=256), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.String(length=64), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['runtime.runs.id'], name=op.f('fk_processed_commands_run_id_runs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_processed_commands')),
    sa.UniqueConstraint('source', 'source_message_id', name='uq_processed_commands_source_message'),
    schema='runtime'
    )
    op.create_index(op.f('ix_runtime_processed_commands_run_id'), 'processed_commands', ['run_id'], unique=False, schema='runtime')
    op.create_table('run_events',
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('sequence', sa.BigInteger(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('body', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runtime.runs.id'], name=op.f('fk_run_events_run_id_runs')),
    sa.PrimaryKeyConstraint('run_id', 'sequence', name=op.f('pk_run_events')),
    schema='runtime'
    )
    op.create_table('spirits',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('spirit_key', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('representative_attribute', sa.String(length=2), nullable=False),
    sa.Column('blessing_item_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.CheckConstraint("representative_attribute IN ('RR', 'YR', 'YY', 'GY', 'GG', 'BG', 'BB', 'PB', 'PP', 'RP')", name=op.f('ck_spirits_representative_attribute_valid')),
    sa.ForeignKeyConstraint(['blessing_item_id'], ['master.items.id'], name=op.f('fk_spirits_blessing_item_id_items')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_spirits')),
    sa.UniqueConstraint('blessing_item_id', name=op.f('uq_spirits_blessing_item_id')),
    sa.UniqueConstraint('spirit_key', name=op.f('uq_spirits_spirit_key')),
    schema='master'
    )
    op.create_table('spirit_item_pool_entries',
    sa.Column('spirit_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['master.items.id'], name=op.f('fk_spirit_item_pool_entries_item_id_items')),
    sa.ForeignKeyConstraint(['spirit_id'], ['master.spirits.id'], name=op.f('fk_spirit_item_pool_entries_spirit_id_spirits')),
    sa.PrimaryKeyConstraint('spirit_id', 'item_id', name=op.f('pk_spirit_item_pool_entries')),
    schema='master'
    )
    op.create_table('run_adventurers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('youtube_id', sa.String(length=256), nullable=False),
    sa.Column('hp', sa.Integer(), nullable=False),
    sa.Column('mp', sa.Integer(), nullable=False),
    sa.Column('base_max_hp', sa.Integer(), nullable=False),
    sa.Column('base_max_mp', sa.Integer(), nullable=False),
    sa.Column('spirit_id', sa.Integer(), nullable=True),
    sa.Column('is_participating', sa.Boolean(), nullable=False),
    sa.Column('is_alive', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runtime.runs.id'], name=op.f('fk_run_adventurers_run_id_runs')),
    sa.ForeignKeyConstraint(['spirit_id'], ['master.spirits.id'], name=op.f('fk_run_adventurers_spirit_id_spirits')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_run_adventurers')),
    sa.UniqueConstraint('run_id', 'youtube_id', name='uq_run_adventurers_run_id_youtube_id'),
    schema='runtime'
    )
    op.create_index(op.f('ix_runtime_run_adventurers_run_id'), 'run_adventurers', ['run_id'], unique=False, schema='runtime')
    op.create_table('run_camps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('floor', sa.Integer(), nullable=False),
    sa.Column('spirit_id', sa.Integer(), nullable=False),
    sa.Column('candidate_a_item_id', sa.Integer(), nullable=False),
    sa.Column('candidate_b_item_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deadline_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('candidate_a_item_id != candidate_b_item_id', name=op.f('ck_run_camps_candidates_distinct')),
    sa.CheckConstraint('deadline_at > started_at', name=op.f('ck_run_camps_deadline_after_start')),
    sa.ForeignKeyConstraint(['candidate_a_item_id'], ['master.items.id'], name=op.f('fk_run_camps_candidate_a_item_id_items')),
    sa.ForeignKeyConstraint(['candidate_b_item_id'], ['master.items.id'], name=op.f('fk_run_camps_candidate_b_item_id_items')),
    sa.ForeignKeyConstraint(['run_id'], ['runtime.runs.id'], name=op.f('fk_run_camps_run_id_runs')),
    sa.ForeignKeyConstraint(['spirit_id'], ['master.spirits.id'], name=op.f('fk_run_camps_spirit_id_spirits')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_run_camps')),
    sa.UniqueConstraint('run_id', 'floor', name='uq_run_camps_run_id_floor'),
    schema='runtime'
    )
    op.create_index(op.f('ix_runtime_run_camps_run_id'), 'run_camps', ['run_id'], unique=False, schema='runtime')
    op.create_table('run_adventurer_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_adventurer_id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('slot', sa.Integer(), nullable=False),
    sa.Column('current_level', sa.Integer(), nullable=False),
    sa.Column('acquired_floor', sa.Integer(), nullable=False),
    sa.Column('acquired_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('current_level >= 1', name=op.f('ck_run_adventurer_items_current_level_positive')),
    sa.CheckConstraint('slot BETWEEN 1 AND 8', name=op.f('ck_run_adventurer_items_slot_in_range')),
    sa.ForeignKeyConstraint(['item_id'], ['master.items.id'], name=op.f('fk_run_adventurer_items_item_id_items')),
    sa.ForeignKeyConstraint(['run_adventurer_id'], ['runtime.run_adventurers.id'], name=op.f('fk_run_adventurer_items_run_adventurer_id_run_adventurers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_run_adventurer_items')),
    sa.UniqueConstraint('run_adventurer_id', 'item_id', name='uq_run_adventurer_items_adventurer_item'),
    sa.UniqueConstraint('run_adventurer_id', 'slot', name='uq_run_adventurer_items_adventurer_slot'),
    schema='runtime'
    )
    op.create_index(op.f('ix_runtime_run_adventurer_items_run_adventurer_id'), 'run_adventurer_items', ['run_adventurer_id'], unique=False, schema='runtime')
    op.create_table('run_camp_members',
    sa.Column('camp_id', sa.UUID(), nullable=False),
    sa.Column('run_adventurer_id', sa.UUID(), nullable=False),
    sa.Column('can_select_action', sa.Boolean(), nullable=False),
    sa.Column('selected_action', sa.String(length=32), nullable=True),
    sa.Column('selected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ready_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('left_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("selected_action IS NULL OR selected_action IN ('rest', 'candidate_a', 'candidate_b', 'forge')", name=op.f('ck_run_camp_members_selected_action_valid')),
    sa.ForeignKeyConstraint(['camp_id'], ['runtime.run_camps.id'], name=op.f('fk_run_camp_members_camp_id_run_camps')),
    sa.ForeignKeyConstraint(['run_adventurer_id'], ['runtime.run_adventurers.id'], name=op.f('fk_run_camp_members_run_adventurer_id_run_adventurers')),
    sa.PrimaryKeyConstraint('camp_id', 'run_adventurer_id', name=op.f('pk_run_camp_members')),
    schema='runtime'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('run_camp_members', schema='runtime')
    op.drop_index(op.f('ix_runtime_run_adventurer_items_run_adventurer_id'), table_name='run_adventurer_items', schema='runtime')
    op.drop_table('run_adventurer_items', schema='runtime')
    op.drop_index(op.f('ix_runtime_run_camps_run_id'), table_name='run_camps', schema='runtime')
    op.drop_table('run_camps', schema='runtime')
    op.drop_index(op.f('ix_runtime_run_adventurers_run_id'), table_name='run_adventurers', schema='runtime')
    op.drop_table('run_adventurers', schema='runtime')
    op.drop_table('spirit_item_pool_entries', schema='master')
    op.drop_table('spirits', schema='master')
    op.drop_table('run_events', schema='runtime')
    op.drop_index(op.f('ix_runtime_processed_commands_run_id'), table_name='processed_commands', schema='runtime')
    op.drop_table('processed_commands', schema='runtime')
    op.drop_table('items', schema='master')
    op.drop_table('enemy_spells', schema='master')
    op.drop_table('runs', schema='runtime')
    op.drop_table('spells', schema='master')
    op.drop_table('enemies', schema='master')
    # ### end Alembic commands ###

    op.execute("DROP SCHEMA IF EXISTS master CASCADE")
    op.execute("DROP SCHEMA IF EXISTS runtime CASCADE")
